name: API Tests

jobs:
  up-and-running:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies with the pipenv
        run: pip install pipenv --user
      - name: Setup Python virtual environment
        run: |
          PATH=$PATH:/home/peter/.local/bin
          pipenv install
      - name: Install development dependencies with the pipenv
      - name: Run tests
        run: |
          pipenv run pytest -s
